[package]
name = "dump_sf7"
description = "Sega SF-7000 floppy file dumper"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
getopts = "0.2.24"
sc3000-charset = { path = "../sc3000-charset" }
sega-basic = { path = "../sega-basic" }
sf7000-fs = { path = "../sf7000-fs" }
